In [1]:
import pandas as pd

In [2]:
url = r'C:\Users\JulianoGarciaGregóri\OneDrive - PerformaIT Cons. e Des. de Softwares\Documentos\estudos-python\Pandas-IO\Aula02\emissoes_CO2.xlsx'
dados_co2 = pd.read_excel(url)

In [8]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [3]:
percapita = pd.read_excel(url, sheet_name='emissoes_percapita')

In [4]:
fontes = pd.read_excel(url, sheet_name='fontes')

In [10]:
intervalo = pd.read_excel(url, sheet_name='emissoes_C02', usecols='A:D')
intervalo.head()

          País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750    0.0
1  Afeganistão                AFG  1751    0.0
2  Afeganistão                AFG  1752    0.0
3  Afeganistão                AFG  1753    0.0
4  Afeganistão                AFG  1754    0.0

In [11]:
intervalo

              País ISO 3166-1 alpha-3   Ano         Total
0      Afeganistão                AFG  1750  0.000000e+00
1      Afeganistão                AFG  1751  0.000000e+00
2      Afeganistão                AFG  1752  0.000000e+00
3      Afeganistão                AFG  1753  0.000000e+00
4      Afeganistão                AFG  1754  0.000000e+00
...            ...                ...   ...           ...
63099       Global                WLD  2017  3.609674e+10
63100       Global                WLD  2018  3.682651e+10
63101       Global                WLD  2019  3.708256e+10
63102       Global                WLD  2020  3.526409e+10
63103       Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [12]:
percapita.to_excel('co2_percapita.xlsx', index=False)

In [17]:
sheet_id = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'

In [18]:
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [19]:
dados = pd.read_csv(url)

In [20]:
dados.to_csv('dados_emissoes_co2.csv', index=False)